### ISSUE TITLE
1=Xb 無法降半調 

### ISSUE THREAD

**Issue by thc282** [Nigh/DoMiSo-Universal#18]
獨立音符可以降半
e.g 3b -4b 
但局域無法降半調
e.g 1=Bb 1=Cb

而且 1=C 和 1=B 用了同一個音階

**Comment by Nigh** [comment]
@thc282 
DoMiSo原神特别版由于游戏机能不支持，导致一些不理解的玩家由于错误的设置了调号而无法正常演奏，已经移除了半音调号。

完整语法在 https://github.com/Nigh/Domiso-origin 原版中支持。
